In [1]:
import numpy as np

### Creating Arrays

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
#2D
b = np.array([[1,2,3],[3,4,5]])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
#3d
c = np.array([[[1,2,3],[3,4,5]],
              [[5,6,7],[8,9,10]]])
c

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 8,  9, 10]]])

In [9]:
#arange - helps in creating an array of evenly sliced values

a = np.arange(1,20,3) #range goes from 1 to 20 with 3 steps 
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
#arange with reshape - it helps in creating muldimensional arrays 
a = np.arange(16).reshape(2,2,2,2) #a 4D array with 16 elements
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [23]:
#generating random numbers
g = np.random.random((3,4))
print(g)
print("")
print("-Please note the double brackets-")

[[0.26925814 0.34556953 0.57184799 0.21656736]
 [0.60999236 0.8805641  0.60891719 0.22976856]
 [0.81172815 0.96989995 0.22416847 0.00238399]]

-Please note the double brackets-


In [24]:
#linspace - generates given number of values between start and stop. Useful for plotting

np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

### Array Attributes

In [25]:
a1 = np.arange(10, dtype = np.int32)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print("-NOTE the three different ways to generate an array-")

-NOTE the three different ways to generate an array-


In [30]:
#ndim - gives the dimension of the array

print(f'Dimension of {a1} is {a1.ndim}\n')
print(f'Dimension of {a2} is {a2.ndim}\n')
print(f'Dimension of {a3} is {a3.ndim}')


Dimension of [0 1 2 3 4 5 6 7 8 9] is 1

Dimension of [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] is 2

Dimension of [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] is 3


In [31]:
#shape - tells the shape i.e. number of elements and rows in the array

print(f'Shape of {a1} is {a1.shape}\n')
print(f'Shape of {a2} is {a2.shape}\n')
print(f'Shape of {a3} is {a3.shape}\n')

Shape of [0 1 2 3 4 5 6 7 8 9] is (10,)

Shape of [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] is (3, 4)

Shape of [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] is (2, 2, 2)



### Changing Datatype

In [32]:
#astype

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])